### ISSUE TITLE
Alignment Process Not Completing Despite High CPU and Memory Allocation

### ISSUE THREAD

**Issue by saharbagheri** [ADAC-UoN/DECIPHER-Sequence-Alignment#2]
Hi,

I've been using DECIPHER package for multiple alignment of my sequencing data from Miseq platform and there was no issue with the default 1 processor and 38G RAM allocation on the cluster. This time I'm trying to align my sequencing data from the Nextseq  platform. I kept receiving out of memory error so I tried different resource allocations as high as 180G and 10 processor but now I'm getting no error and the job submitted times out before finishing. 

I was wondering if there is anything else I can do to improve this process or if I should try other tools.

Thanks,
Sahar

**Comment by addyblanch** [comment]
Hi Sahar, 

This is just an internal script we use to align regions of bacteria genomes. You will be better asking the creator of Decipher at http://www2.decipher.codes/Contact.html
